project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Jiahao Zhang"
  site-url: https://zhangjh358.github.io
  favicon: images/logo.jpg
  repo-url: https://github.com/zhangjh358/zhangjh358.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: CVZJH.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细